---
language: python

jobs:
  include:
    - name: "Python 3.8"
      python: "3.8"
      install:
        - pip install -r requirements.txt
      script:
        - cp .env.example .env
        - python3 ./manage.py test
    - name: "flake8"
      python: "3.8"
      install:
        - pip install -r test-requirements.txt
      script:
        - flake8 --exclude .venv .
